16-01-2020:22:27:10 ERROR    [11.Practicing logging.py:9] Error
16-01-2020:22:27:10 ERROR    [11.Practicing logging.py:12] Error
